# Generated by Django 5.1.2 on 2026-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_task_is_completed_task_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_latitude',
            field=models.FloatField(blank=True, default=17.385, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_longitude',
            field=models.FloatField(blank=True, default=78.4867, null=True),
        ),
    ]
